### ISSUE TITLE
can't install metview for python, but can use metview via Eccodes

### ISSUE THREAD

**Issue by Ultiseeker** [ecmwf/metview-python#13]
Hello developers of Metview Python,

I was trying to install metview for python with the pip install metview.
The pip install worked, I used 'sudo pip3 install metview'
After that I used the python -m metview selfcheck (returned with I got python 2.7.12)
so I used python3 -m metview selfcheck and I got back an error.

I've added a screenshot mayby it makes it a bit more clear.

Can you help me set up Metview for python (python 3)

I tried to install it in:
- a VM with ubuntu 16.04
- it has python 2 and 3
- Eccodes is installed

![metview problem](https://user-images.githubusercontent.com/52050151/59875512-40f00400-93a1-11e9-8173-8da602d304d0.jpg)

**Comment by iainrussell** [comment]
Hi @Ultiseeker ,

I think the problem is that the version of Metview that comes with Ubuntu 16.04 is too old to support the Python interface. Even with newer editions of Ubuntu, we've seen problems with the packaging of Metview, so I'd advise that you try either:
* the development version that's available on conda (not 'officially' released yet, but it's there, so you can try it). If you can install a conda environment, then this command will install a recent Metview into it: "conda install -c conda-forge metview" - then you can also do "pip install metview" into the same environment. I haven't tried this on an older system like Ubuntu 16, so I can't guarantee it will work, but it's worth a go.
* OR build Metview from source, probably the source bundle is best for this: https://confluence.ecmwf.int/display/METV/The+Metview+Source+Bundle  Again, we're not testing much on these older platforms, but as long as it has a reasonably recent GNU compiler (>=6) then it should be possible.

I hope this helps a bit!
Iain

**Comment by Ultiseeker** [comment]
Thanks Iain,

First option works.

Flow up question.
I want to export a .grib file into a pandas dataframe.
is that possible?

**Comment by iainrussell** [comment]
Hi @Ultiseeker ,

That's great - glad you got it working!

Interesting question about GRIB to dataframe. How would you like to see the dataframe organised? Here's some code that will give you a simple lat/lon/value dataframe from a single GRIB field. How to handle multiple fields would be an interesting question!

```
import metview as mv
import pandas as pd

grib = mv.read("ERA5_levels.grib")[0]

df = pd.DataFrame({'latitude' : grib.latitudes(),
                   'longitude' :grib.longitudes(),
                   'value' :    grib.values()})
print(df)
```
Iain
