### ISSUE TITLE
multiple metview files in tmp directory

### ISSUE THREAD

**Issue by gkafk** [ecmwf/metview-python#29]
Any idea why this happens?
![Screenshot 2021-06-11 231217](https://user-images.githubusercontent.com/64424891/121960852-53725d80-cd6f-11eb-98ff-079513e51589.jpg)

How can I avoid it? It can use more than 2GB disk space.

**Comment by iainrussell** [comment]
Hi,

Normally these should not be left behind on the system. Each time you run Metview, it creates a temporary directory which then gets deleted when you quit Metview. When you import Metview through Python, it essentially starts a lightweight Metview session, which creates this directory. It should all be deleted if the Python session terminates properly - so the fact that you have some of these suggests that you had some sessions that did not end cleanly, or else there's something wrong with our mechanism for detecting the end of a session. I remember that Python gets into quite a chaotic state when it is shutting down, but I thought we had a reasonable solution for it.

It's hard to know programatically when we can delete old temp dirs, because they could, in theory, still be in use by a running session (you can run as many simultaneous sessions as you want), so we do not perform an automatic cleanup of 'old' dirs. I guess it would be interesting to know if the number of these temp dirs is the same as the number of times you've used Metview, or if you think that most of the dirs are cleaned up and these are exceptions.

Best regards,
Iain
