### ISSUE TITLE
Problem filtering for single latitude longitude grid point using read

### ISSUE THREAD

**Issue by SpechtacularDave** [ecmwf/metview-python#40]
Hello,

I am trying to read a grib file and filter it for a single lat/long coordinate. The docs for [read](https://metview.readthedocs.io/en/latest/gen_files/icon_functions/read.html#id0) state that the latitude and longitude parameters can be passed strings to filter on, but I'm not getting any data in the returned fieldset when I do so. My source file contains the area of [30.5, -100.5, 30, -100] on a 0.25 degree grid, and here is my line of code:

fs = mv.read(source='download.grib', latitude='30.25', longitude='-100.25')

I tried passing floats too, but that also doesn't work.  
fs2 = mv.read(source='download.grib', latitude=30.25, longitude=-100.25)

When I run latitudes() on either of the previous result fieldsets, I get AttributeError: 'NoneType' object has no attribute 'latitudes'

I am able to filter by area, but you don't seem to be able to specify a single point with it.
fs = mv.read(source='download.grib', area=[30.25, -100.25, 30, -100])

Any idea what I am doing wrong? I've searched all over the docs for an example showing how to use the latitude and longitude parameters, but wasn't able to find one. If it helps, attached is a script that downloads a small amount of data and tries to filter on a specific latitude and longitude.
[metviewLatLongFilterProblem.txt](https://github.com/ecmwf/metview-python/files/7997007/metviewLatLongFilterProblem.txt)

Thanks, -David

**Comment by sandorkertesz** [comment]
Hi David, 

The [read](https://metview.readthedocs.io/en/latest/gen_files/icon_functions/read.html#id0) function is basically the same as [retrieve](https://metview.readthedocs.io/en/latest/gen_files/icon_functions/read.html#id0), but it works on a GRIB file instead of retrieving data from the MARS archive. From the **retrieve** documentation you find a link to the [MARS documentation](https://confluence.ecmwf.int/display/UDOC/Keywords+in+MARS+and+Dissemination+requests) which states that e.g. **latitude**: 

_"Specifies the location in longitude for meridionally oriented or time-series ocean field product."_

So **read/retrieve** cannot be used for point data extraction. If you want to extract point data from GRIB you can use the [nearest_gridpoint](https://metview.readthedocs.io/en/latest/api/functions/nearest_gridpoint.html) or [interpolate](https://metview.readthedocs.io/en/latest/api/functions/interpolate.html) functions. They both result in **values/arrays**, this [notebook](https://metview.readthedocs.io/en/latest/examples/grib_interpolation.html) gives you a few examples. 

I hope this is what you need, but if you want to store the single extracted value in GRIB format please let us  know.

Kind regards,
Sandor

**Comment by SpechtacularDave** [comment]
Hi Sandor,

Thank you for the information. I see now that those parameters have a different purpose than I was thinking. I can probably work around this by just using nearest_gridpoint, but could you provide any more information on how I would go about extracting to grib format?

Thanks, -David

**Comment by iainrussell** [comment]
Hi David,

The AREA parameter can let you specify the region you'd like to store in GRIB, e.g. something like:
fs = mv.read(source='download.grib', area=[30.28, -100.28, 30.22, -100.22]) # [N,W,S,E]

I'm not 100% sure that a single-point GRIB is possible, so you may need to expand the area box a little and get more points.

Cheers,
Iain

**Comment by SpechtacularDave** [comment]
Hi Iain,

Gotcha, I should be able to make do with setting a small area instead.

Thanks!
David
